name: minimalistic_push
description: A minimalistic push-up application.

publish_to: 'none' # do not remove

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # common
  clipboard: ^0.1.3
  proximity_sensor: ^1.0.2
  share_plus: ^4.0.4
  sqflite: ^2.0.2+1
  url_launcher: ^6.1.2

  # get
  get: ^4.6.3
  get_storage: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  effective_dart: ^1.3.0


flutter_icons:
  image_path: 'assets/icons/app_icon.png'
  android: false
  ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/icons/app_icon.png